vich_uploader:
    db_driver: orm
    mappings:
        # Configuration for your entity
        upload_images:
            uri_prefix: /upload/thumbnail
            upload_destination: '%kernel.project_dir%/public/upload/thumbnail'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
