home:
  path: /
  controller: 'App\Controller\HomeController::index'
app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
